id: cn.wps.office
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: wps
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --persist=.kingsoft
  - --env=TMPDIR=/var/tmp
  - --filesystem=xdg-documents
  - --filesystem=xdg-download
  - --filesystem=xdg-pictures
  - --filesystem=xdg-videos
  - --filesystem=/run/media
  - --filesystem=/media
  - --env=QT_PLUGIN_PATH=/app/lib/qt/plugins:/app/extra/wps-office/office6/qt/plugins

cleanup:
  - "*.a"
  - "*.la"
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - shared-modules/SDL2/SDL2-with-libdecor.json

  - shared-modules/glu/glu-9.json

  # Needed by wpspdf
  - name: libtiff5
    buildsystem: cmake
    sources:
      - type: archive
        url: https://download.osgeo.org/libtiff/tiff-4.4.0.tar.gz
        sha256: 917223b37538959aca3b790d2d73aa6e626b688e02dcda272aec24c2f498abed

  # https://github.com/flathub/cn.wps.office/issues/150
  - name: freetype
    buildsystem: meson
    sources:
      - type: archive
        url: https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.13.0.tar.xz
        sha256: 5ee23abd047636c24b2d43c6625dcafc66661d1aca64dec9e0d05df29592624c

  - name: wps
    buildsystem: simple
    build-commands:
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t /app/share/metainfo/
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv opt/kingsoft/wps-office /app
      - mv usr/bin/{wps,wpp,et,wpspdf} /app/wps-office/
      - mv usr/share/{icons,applications,mime} /app/share/
      - install -Dm755 wps.sh /app/bin/wps
      - ln -s wps /app/bin/et
      - ln -s wps /app/bin/wpp
      - ln -s wps /app/bin/wpspdf
      # Just use libstdc++.so.6 from the runtime; allows working with runtime 23.08+
      - rm /app/wps-office/office6/libstdc++.so.6
      # Fix wps deprecated python2 command
      # https://aur.archlinux.org/cgit/aur.git/tree/fix-wps-python-parse.patch?h=wps-office-cn
      - sed -i 's/python -c '\''import sys, urllib; print urllib.unquote(sys.argv\[1\])'\''/python -c '\''import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))'\''/' /app/wps-office/wps
      # Rename
      - rename --no-overwrite "wps-office-" "${FLATPAK_ID}." /app/share/{icons/hicolor/*/*,applications,mime/packages}/wps-office-*.*
      - rename --no-overwrite "wps-office2019-" "${FLATPAK_ID}." /app/share/icons/hicolor/*/*/wps-office2019-*.*
      - sed -i "s/generic-icon name=\"wps-office-/icon name=\"${FLATPAK_ID}./g" "/app/share/mime/packages/${FLATPAK_ID}".*.xml
      - |
        for a in wps wpp et pdf prometheus; do
            desktop_file="/app/share/applications/${FLATPAK_ID}.$a.desktop"
            appbin="$a"
            appicon="${FLATPAK_ID}.${a}main"
            case "$a" in
                pdf)
                    appbin=wpspdf
                ;;
                prometheus)
                    appbin=wps
                    appicon="${FLATPAK_ID}.k${a}"
                    # Use this as the main .desktop file for the Flatpak
                    new_desktop_file="$(dirname $desktop_file)/${FLATPAK_ID}.desktop"
                    mv $desktop_file $new_desktop_file
                    desktop_file=$new_desktop_file
                ;;
            esac
            desktop-file-edit \
                --set-key="Exec" --set-value="$appbin %f" \
                --set-key="Icon" --set-value="$appicon" \
                --set-key="X-Flatpak-RenamedFrom" --set-value="wps-office-$a.desktop;" \
                "$desktop_file"
        done

    sources:
      - type: file
        path: cn.wps.office.metainfo.xml

      - type: file
        path: wps.sh

      - type: file
        filename: wps-office.deb
        only-arches: [x86_64]
        url: https://mirrors.nju.edu.cn/ubuntukylin/pool/partner/wps-office_11.1.0.11723_amd64.deb
        sha256: 53e0b0f37e7568f6e763aa13f14940e2ed97168e185fcb30095ab80119690623
        x-checker-data:
          type: debian-repo
          package-name: wps-office
          root: https://mirrors.nju.edu.cn/ubuntukylin
          dist: jammy-partner
          component: main
