app-id: top.jtmonster.jhentai
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: jhentai
finish-args:
  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'
  - '--share=network'
  - '--device=dri'
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - webkit2gtk4.0.yaml
  - name: jhentai
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv usr/share/applications /app/share/
      - mv usr/share/icons /app/share/
      - mv opt/jhentai /app/
      - install -Dm755 jhentai.sh /app/bin/jhentai
      - install -Dm644 top.jtmonster.jhentai.metainfo.xml -t /app/share/metainfo
    sources:
      - type: archive
        url: https://nightly.link/jiangtian616/JHenTai/workflows/build_publish/3.19.x-linux/release-Linux.zip
        dest-filename: jhentai.zip
        sha256: 2cbe6f2a94a373c591e51d3c5244b85b7323b794a5e4109c797f8588f3ed74be
      - type: file
        path: top.jtmonster.jhentai.metainfo.xml
      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - exec /app/jhentai/jhentai "$@"
        dest-filename: jhentai.sh
