app-id: com.qq.qq
runtime: org.gnome.Platform
runtime-version: '45'
sdk: org.gnome.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '23.08'
command: qq
rename-icon: qq
rename-desktop-file: qq.desktop
separate-locales: false

finish-args:
  - --share=ipc
  - --share=network
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=dri
  - --filesystem=xdg-download
  - --talk-name=org.gnome.Shell.Screencast
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --system-talk-name=org.freedesktop.login1

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '23.08'
    add-ld-path: .

modules:
  # runtime cups is built aginst openssl
  # need cups with gnutls for qq to load gnutls func
  - name: cups
    config-opts:
      - --with-components=all
      - --with-dbusdir=/etc/dbus-1
      - --with-systemd
      - --with-tls=gnutls
      - --with-cups-group=lp
      - --with-system-groups=wheel
      - --with-rundir=/run/cups
      - localedir=/usr/share/locale
    no-make-install: true
    post-install:
      - install -Dm755 cups/libcups.so $FLATPAK_DEST/lib/libcups.so.2
    sources:
      - type: git
        url: https://github.com/OpenPrinting/cups.git
        tag: v2.4.7
        commit: 3a4d9204e5818e5d0b8f1e0e50832661209048ee
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$

  - name: librename
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/etc/preload
      - g++ -shared -fPIC -o rename.so rename.cpp -ldl
      - install -Dm755 ./rename.so -t $FLATPAK_DEST/etc/preload/
    sources:
      - type: file
        path: patch/rename.cpp

  - name: qq
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf qq.deb data.* | bsdtar -xf -
      - rm -r usr/share/doc
      - mv opt/QQ $FLATPAK_DEST/
      - cp -a usr/share $FLATPAK_DEST/
      - desktop-file-edit --set-key="Exec" --set-value="qq %U" $FLATPAK_DEST/share/applications/qq.desktop
      - install -Dm644 com.qq.qq.metainfo.xml -t /app/share/metainfo
      - install -Dm755 qq.sh /app/bin/qq
      - mkdir -p /app/lib/ffmpeg
    sources:
      - type: file
        dest-filename: qq.deb
        only-arches:
          - aarch64
        url: https://dldir1.qq.com/qqfile/qq/QQNT/852276c1/linuxqq_3.2.5-21453_arm64.deb
        sha256: 8342751561b4edb91a6c31e9da7b92e3c30dbaddbe37b824d24e7359c9ae415c
      - type: file
        dest-filename: qq.deb
        only-arches:
          - x86_64
        url: https://dldir1.qq.com/qqfile/qq/QQNT/852276c1/linuxqq_3.2.5-21453_amd64.deb
        sha256: e907b86cfdeaf512c42099fd11faaa61a55317c15104d723b553e5fb363bbf97
      - type: file
        path: com.qq.qq.metainfo.xml
      - type: script
        dest-filename: qq.sh
        commands:
          - export ZYPAK_LD_PRELOAD="/app/etc/preload/rename.so"
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - exec zypak-wrapper /app/QQ/qq --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime "$@"
