app-id: io.github.MCDFsteve.FnipaPlay
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: fnipaplay
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.freedesktop.Notifications
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '23.08'
    add-ld-path: .

modules:
  - name: libass
    config-opts:
      - --disable-static
    sources:
      - type: archive
        url: https://github.com/libass/libass/releases/download/0.17.3/libass-0.17.3.tar.gz
        sha256: da7c348deb6fa6c24507afab2dee7545ba5dd5bbf90a137bfe9e738f7df68537
        x-checker-data:
          type: anitya
          project-id: 1560
          stable-only: true
          url-template: https://github.com/libass/libass/releases/download/$version/libass-$version.tar.gz

  - name: fnipaplay
    buildsystem: simple
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv opt/fnipaplay /app/
      - cp -a usr/share /app/
      - chmod +x /app/fnipaplay/fnipaplay
      - install -Dm755 fnipaplay.sh /app/bin/fnipaplay
      - install -Dm644 io.github.MCDFsteve.FnipaPlay.metainfo.xml -t /app/share/metainfo
      - ln -svf /usr/bin/ffmpeg /app/bin/
      - mkdir -p /app/lib/ffmpeg
    sources:
      - type: file
        url: https://github.com/MCDFsteve/FnipaPlay/releases/download/0.0.5.1/FnipaPlay-0.0.6+1-Linux-amd64.deb
        dest-filename: fnipaplay.deb
        sha256: c5d80e6c07a54495a931b9072c68d8c4d6c4465ae20f8446e1e56e62a2c3bf7e
      - type: file
        path: io.github.MCDFsteve.FnipaPlay.metainfo.xml
      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/fnipaplay/fnipaplay
        dest-filename: fnipaplay.sh
