id: org.freedesktop.Sdk.Extension.dart
branch: '23.08'
runtime: org.freedesktop.Sdk
build-extension: true
sdk: org.freedesktop.Sdk
runtime-version: '23.08'
separate-locales: false
appstream-compose: false

modules:
  - name: dart
    buildsystem: simple
    build-commands:
      - install -d /usr/lib/sdk/dart
      - cp -a * /usr/lib/sdk/dart/
    sources:
      - type: archive
        only-arches:
          - aarch64
        url: https://storage.googleapis.com/dart-archive/channels/stable/release/3.5.0/sdk/dartsdk-linux-arm64-release.zip
        sha256: ee2cbcc36a190a883254ddc28ef772c15735022bfc5cfc11a56dbaebd5353903
        x-checker-data:
          type: anitya
          project-id: 14718
          stable-only: true
          url-template: https://storage.googleapis.com/dart-archive/channels/stable/release/$version/sdk/dartsdk-linux-arm64-release.zip
      - type: archive
        only-arches:
          - x86_64
        url: https://storage.googleapis.com/dart-archive/channels/stable/release/3.5.0/sdk/dartsdk-linux-x64-release.zip
        sha256: 011a1dd6ff4e0bb4a168f7b4e13063514fbc255dc52d1ad660bf5a28773e9773
        x-checker-data:
          type: anitya
          project-id: 14718
          stable-only: true
          url-template: https://storage.googleapis.com/dart-archive/channels/stable/release/$version/sdk/dartsdk-linux-x64-release.zip
      - type: archive
        only-arches:
          - arm
        url: https://storage.googleapis.com/dart-archive/channels/stable/release/3.5.0/sdk/dartsdk-linux-arm-release.zip
        sha256: 011a1dd6ff4e0bb4a168f7b4e13063514fbc255dc52d1ad660bf5a28773e9773
        x-checker-data:
          type: anitya
          project-id: 14718
          stable-only: true
          url-template: https://storage.googleapis.com/dart-archive/channels/stable/release/$version/sdk/dartsdk-linux-arm-release.zip
      - type: archive
        only-arches:
          - i386
        url: https://storage.googleapis.com/dart-archive/channels/stable/release/3.5.0/sdk/dartsdk-linux-ia32-release.zip
        sha256: 011a1dd6ff4e0bb4a168f7b4e13063514fbc255dc52d1ad660bf5a28773e9773
        x-checker-data:
          type: anitya
          project-id: 14718
          stable-only: true
          url-template: https://storage.googleapis.com/dart-archive/channels/stable/release/$version/sdk/dartsdk-linux-ia32-release.zip

  - name: scripts
    buildsystem: simple
    sources:
      - type: script
        commands:
          - export DARTROOT=/usr/lib/sdk/dart
          - export PATH=$PATH:$DARTROOT/bin
        dest-filename: enable.sh
    build-commands:
      - cp enable.sh /usr/lib/sdk/dart/

  - name: appdata
    buildsystem: simple
    sources:
      - type: file
        path: org.freedesktop.Sdk.Extension.dart.metainfo.xml
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/share/metainfo
      - cp ${FLATPAK_ID}.metainfo.xml ${FLATPAK_DEST}/share/metainfo
      - appstream-compose --basename ${FLATPAK_ID} --prefix=${FLATPAK_DEST} --origin=flatpak
        ${FLATPAK_ID}
