id: org.freedesktop.xorg.xeyes
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: xeyes
finish-args:
  - --socket=x11
  - --device=dri
  - --share=ipc

cleanup:
  - /lib/pkgconfig
  - /share/man
  - /share/doc
  - /include
  - /lib/*.a

modules:
  - name: libXmu
    buildsystem: autotools
    sources:
      - type: archive
        url: https://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.4.tar.gz
        sha256: 3091d711cdc1d8ea0f545a13b90d1464c3c3ab64778fd121f0d789b277a80289
        x-checker-data:
          type: anitya
          project-id: 1785
          url-template: https://xorg.freedesktop.org/releases/individual/lib/libXmu-$version.tar.gz

  - name: xeyes
    buildsystem: autotools
    post-install:
      - install -Dm644 $FLATPAK_ID.png -t $FLATPAK_DEST/share/icons/hicolor/512x512/apps
      - install -Dm644 $FLATPAK_ID.desktop -t $FLATPAK_DEST/share/applications
      - install -Dm644 $FLATPAK_ID.metainfo.xml -t $FLATPAK_DEST/share/metainfo
    sources:
      - type: archive
        url: https://xorg.freedesktop.org/archive/individual/app/xeyes-1.3.0.tar.xz
        sha256: 0950c600bf33447e169a539ee6655ef9f36d6cebf2c1be67f7ab55dacb753023
        x-checker-data:
          type: anitya
          project-id: 15025
          is-main-source: true
          url-template: https://xorg.freedesktop.org/archive/individual/app/xeyes-$version.tar.xz
      - type: file
        path: org.freedesktop.xorg.xeyes.png
      - type: file
        path: org.freedesktop.xorg.xeyes.desktop
      - type: file
        path: org.freedesktop.xorg.xeyes.metainfo.xml
