app-id: com.qq.docs
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '23.08'
separate-locales: false
command: tdappdesktop

finish-args:
  - --share=ipc
  - --socket=x11
  - --device=dri
  - --share=network
  - --filesystem=xdg-download
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - name: docs
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm755 apply_extra -t /app/bin
      - install -Dm644 com.qq.docs.svg -t /app/share/icons/hicolor/scalable/apps
      - install -Dm644 com.qq.docs.desktop -t /app/share/applications
      - install -Dm644 com.qq.docs.metainfo.xml -t /app/share/metainfo
      - install -Dm755 tdappdesktop.sh /app/bin/tdappdesktop
    sources:
      - type: extra-data
        only-arches: [aarch64]
        filename: docs.deb
        url: https://desktop.docs.qq.com/Installer/30001/3.6.3/TencentDocs-arm64.deb
        sha256: 0853a1fdd7ae82da331ee49568b9d9f3fc5f5c5cc26e6eeb0261035b5b0b81bb
        size: 145707978
      - type: extra-data
        only-arches: [x86_64]
        filename: docs.deb
        url: https://desktop.docs.qq.com/Installer/30001/3.6.3/TencentDocs-x64.deb
        sha256: 4c767f2c03ccd892445b2358382596767bcf2047869be39ed8a9845ff7224309
        size: 150979840
      - type: file
        path: com.qq.docs.metainfo.xml
      - type: file
        path: com.qq.docs.svg
      - type: file
        path: com.qq.docs.desktop
      - type: script
        dest-filename: tdappdesktop.sh
        commands:
          - export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID
          - exec zypak-wrapper.sh /app/docs/tdappdesktop "$@"
      - type: script
        commands:
          - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
          - mv opt/腾讯文档 ./docs
          - rm -rf *.deb usr opt
        dest-filename: apply_extra
