app-id: com.qq.docs
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '23.08'
separate-locales: false
rename-icon: tdappdesktop
rename-desktop-file: tdappdesktop.desktop
command: tdappdesktop

finish-args:
  - --share=ipc
  - --socket=x11
  - --device=dri
  - --share=network
  - --filesystem=xdg-download
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - name: docs
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf docs.deb data.* | bsdtar -xf -
      - rm -r usr/share/doc
      - mv opt/腾讯文档 $FLATPAK_DEST/docs
      - cp -a usr/share $FLATPAK_DEST/
      - desktop-file-edit --set-key="Exec" --set-value="tdappdesktop %U" $FLATPAK_DEST/share/applications/tdappdesktop.desktop
      - install -Dm644 com.qq.docs.metainfo.xml -t /app/share/metainfo
      - install -Dm755 tdappdesktop.sh /app/bin/tdappdesktop
    sources:
      - type: file
        dest-filename: docs.deb
        only-arches:
          - aarch64
        url: https://desktop.docs.qq.com/Installer/30001/3.5.4/TencentDocs-arm64.deb
        sha256: dca401a683e13f1c525f715b2fb2362b32e9fa0ec1a2b450b61e7f309bcfa4b7
      - type: file
        dest-filename: docs.deb
        only-arches:
          - x86_64
        url: https://desktop.docs.qq.com/Installer/30001/3.5.4/TencentDocs-x64.deb
        sha256: 3e46e878ccb5725db5045f4ebf641bb8e47bd29be04f82a4ec4139985d762673
      - type: file
        path: com.qq.docs.metainfo.xml
      - type: script
        dest-filename: tdappdesktop.sh
        commands:
          - export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID
          - exec zypak-wrapper.sh /app/docs/tdappdesktop "$@"
