on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 12 * * 0" # 每星期天中午12点运行一次
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
name: Build
jobs:
  freedesktop-x86_64:
    name: freedesktop-x86_64
    runs-on: ubuntu-latest
    container: 
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    strategy: 
      matrix: 
        appid: 
          # - cn.wps.office
          # - com.qq.docs
          # - com.qq.qqmusic
          # - com.xiaoyaocz.dmzjx
          - com.xiaoyaocz.simplelive
          # - io.github.MCDFsteve.FnipaPlay
          # - io.github.msojocs.bilibili
          # - org.freedesktop.xorg.xeyes
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: freedesktop x86_64
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ matrix.appid }}-x86_64.flatpak
          manifest-path: manifests/${{ matrix.appid }}/${{ matrix.appid }}.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: x86_64

  # freedesktop-aarch64:
  #   name: freedesktop-aarch64
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
  #     options: --privileged
  #   strategy: 
  #     matrix: 
  #       appid: 
  #         - com.qq.docs
  #         - com.qq.qqmusic
  #         - io.github.msojocs.bilibili
  #         - org.freedesktop.xorg.xeyes
  #     # Don't fail the whole workflow if one architecture fails
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'
  #     # Docker is required by the docker/setup-qemu-action which enables emulation
  #     - name: Install deps
  #       run: |
  #         dnf -y install docker
  #     - name: Set up QEMU
  #       id: qemu
  #       uses: docker/setup-qemu-action@v2
  #       with:
  #         platforms: arm64
  #     - name: freedesktop aarch64
  #       uses: flatpak/flatpak-github-actions/flatpak-builder@v6
  #       with:
  #         bundle: ${{ matrix.appid }}-aarch64.flatpak
  #         manifest-path: manifests/${{ matrix.appid }}/${{ matrix.appid }}.yaml
  #         cache-key: flatpak-builder-${{ github.sha }}
  #         arch: aarch64

  # kde-x86_64:
  #   name: kde-x86_64
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: bilelmoussaoui/flatpak-github-actions:kde-6.7
  #     options: --privileged
  #   strategy: 
  #     matrix: 
  #       appid: 
  #         - io.github.c0re100.qBittorrent-Enhanced-Edition
  #     # Don't fail the whole workflow if one architecture fails
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'
  #     - name: kde x86_64
  #       uses: flatpak/flatpak-github-actions/flatpak-builder@v6
  #       with:
  #         bundle: ${{ matrix.appid }}-x86_64.flatpak
  #         manifest-path: manifests/${{ matrix.appid }}/${{ matrix.appid }}.yaml
  #         cache-key: flatpak-builder-${{ github.sha }}
  #         arch: x86_64

  # kde-aarch64:
  #   name: kde-aarch64
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: bilelmoussaoui/flatpak-github-actions:kde-6.7
  #     options: --privileged
  #   strategy: 
  #     matrix: 
  #       appid: 
  #         - io.github.c0re100.qBittorrent-Enhanced-Edition
  #     # Don't fail the whole workflow if one architecture fails
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'
  #     # Docker is required by the docker/setup-qemu-action which enables emulation
  #     - name: Install deps
  #       run: |
  #         dnf -y install docker
  #     - name: Set up QEMU
  #       id: qemu
  #       uses: docker/setup-qemu-action@v2
  #       with:
  #         platforms: arm64
  #     - name: kde aarch64
  #       uses: flatpak/flatpak-github-actions/flatpak-builder@v6
  #       with:
  #         bundle: ${{ matrix.appid }}-aarch64.flatpak
  #         manifest-path: manifests/${{ matrix.appid }}/${{ matrix.appid }}.yaml
  #         cache-key: flatpak-builder-${{ github.sha }}
  #         arch: aarch64

  # gnome-x86_64:
  #   name: gnome-x86_64
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: bilelmoussaoui/flatpak-github-actions:gnome-46
  #     options: --privileged
  #   strategy: 
  #     matrix: 
  #       appid: 
  #         - top.jtmonster.jhentai
  #         - io.github.predidit.kazumi
  #     # Don't fail the whole workflow if one architecture fails
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'
  #     - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
  #       with:
  #         bundle: ${{ matrix.appid }}-x86_64.flatpak
  #         manifest-path: manifests/${{ matrix.appid }}/${{ matrix.appid }}.yaml
  #         cache-key: flatpak-builder-${{ github.sha }}
  #         arch: x86_64
  Publish:
    name: Publish
    needs: freedesktop-x86_64
    # needs: [freedesktop-x86_64, freedesktop-aarch64, kde-x86_64, kde-aarch64, gnome-x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make tmp dir
        run: mkdir /tmp/artifacts
      - name: Download all Artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
          merge-multiple: true
      - name: List all Artifacts
        run: ls -R /tmp/artifacts
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: ContinuousBuild
          allowUpdates: true
          artifacts: /tmp/artifacts/**/*.flatpak
          artifactErrorsFailBuild: true
          replacesArtifacts: true
